channels:
  - UC-b89a0Fw6pNoP-g-_qLeiw
  - UC2q4mHrzoR48mwSuAYtVPtQ
  - UC3bZgJqT_LfwLfeOtDgO88A
  - UC5xLYlJwLEWKedeliRnMPug
  - UC6If-LcFxUDJhgL9dmB8oMA
  - UC7scMfFypUV7T3d9PiV23oA
  - UC9MK8SybZcrHR3CUV4NMy2g
  - UCCr5a9lf6LtGMvOX4gz0iug
  - UCGSqw82Zny7_z-QLpyMAxIw
  - UCGvQAPkKzSeWu6mhZKrGx_Q
  - UCIQ1PyEVzV2sc4CXHKH2cSg
  - UCM7-8EfoIv0T9cCI4FhHbKQ
  - UCOxQWb-OuyCSZadzWqrKTCQ
  - UCUyeluBRhGPCW4rPe_UvBZQ
  - UCUzkWdUCkVrkKCcmut9epTQ
  - UCd190n-WQVHPC2l5gu0E2QQ
  - UCjay7c-KSW2nC8Grq_q8tHg
  - UCk73U4QT3cNDvqb_PaWM8AA
  - UCkUe2e1YuRtBRRaP2XTupwg
  - UCoEhy7X8n7goJIyy-nLCxGg
  - UCpFXaEz3vKJ45XjW5m5pbow
  - UCtQJxXLYUhdfkr8jgGfzdMA
  - UCtihVU6wLYu09x_oW7LCAtA
  - UCwipTluVS2mjuhPtx2WU7eQ
  - UCyTXjkYDt1t3lH1UErSILvw
  - UCDGytyBxhU_b-OFcbLCdJSw
  - UC8M5YVWQan_3Elm-URehz9w
  - UC1tGyMwuF6hUHRp2syrADOQ
  - UClusShJbD5SIMuoF9Ql5hOw
  - UC101o-vQ2iOj9vr00JUlyKw
  - UC9XJvt8OT-9_8QHDBdqocaw
  - UClOA6fePoku3XBBxKrSLpuw
  - UCqFjrhGSX6vIGoHTnxk9sIg
  - UC5eNHOA5OZtqJc6PvtUFfYw
