feeds:
  - type: youtube
    url: UC-b89a0Fw6pNoP-g-_qLeiw
  - type: youtube
    url: UC2q4mHrzoR48mwSuAYtVPtQ
  - type: youtube
    url: UC3bZgJqT_LfwLfeOtDgO88A
  - type: youtube
    url: UC5xLYlJwLEWKedeliRnMPug
  - type: youtube
    url: UC6If-LcFxUDJhgL9dmB8oMA
  - type: youtube
    url: UC7scMfFypUV7T3d9PiV23oA
  - type: youtube
    url: UC9MK8SybZcrHR3CUV4NMy2g
  - type: youtube
    url: UCCr5a9lf6LtGMvOX4gz0iug
  - type: youtube
    url: UCGSqw82Zny7_z-QLpyMAxIw
  - type: youtube
    url: UCGvQAPkKzSeWu6mhZKrGx_Q
  - type: youtube
    url: UCIQ1PyEVzV2sc4CXHKH2cSg
  - type: youtube
    url: UCM7-8EfoIv0T9cCI4FhHbKQ
  - type: youtube
    url: UCOxQWb-OuyCSZadzWqrKTCQ
  - type: youtube
    url: UCUyeluBRhGPCW4rPe_UvBZQ
  - type: youtube
    url: UCUzkWdUCkVrkKCcmut9epTQ
  - type: youtube
    url: UCd190n-WQVHPC2l5gu0E2QQ
  - type: youtube
    url: UCjay7c-KSW2nC8Grq_q8tHg
  - type: youtube
    url: UCk73U4QT3cNDvqb_PaWM8AA
  - type: youtube
    url: UCkUe2e1YuRtBRRaP2XTupwg
  - type: youtube
    url: UCoEhy7X8n7goJIyy-nLCxGg
  - type: youtube
    url: UCpFXaEz3vKJ45XjW5m5pbow
  - type: youtube
    url: UCtQJxXLYUhdfkr8jgGfzdMA
  - type: youtube
    url: UCtihVU6wLYu09x_oW7LCAtA
  - type: youtube
    url: UCwipTluVS2mjuhPtx2WU7eQ
  - type: youtube
    url: UCyTXjkYDt1t3lH1UErSILvw
  - type: youtube
    url: UCDGytyBxhU_b-OFcbLCdJSw
  - type: youtube
    url: UC8M5YVWQan_3Elm-URehz9w
  - type: youtube
    url: UC1tGyMwuF6hUHRp2syrADOQ
  - type: youtube
    url: UClusShJbD5SIMuoF9Ql5hOw
  - type: youtube
    url: UC101o-vQ2iOj9vr00JUlyKw
  - type: youtube
    url: UC9XJvt8OT-9_8QHDBdqocaw
  - type: youtube
    url: UClOA6fePoku3XBBxKrSLpuw
  - type: youtube
    url: UCqFjrhGSX6vIGoHTnxk9sIg
  - type: youtube
    url: UC5eNHOA5OZtqJc6PvtUFfYw
  - type: youtube
    url: UCtmKLC__fMtR0NIN4-MRkug
  - type: rss
    url: https://dou.ua/forums/feed/tag/tech/
  - type: rss
    url: https://dou.ua/lenta/news/feed/
  - type: rss
    url: https://rubyland.news/feed.rss
